server:
  port: 8082

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  massages:
    basename: massages
    encoding: UTF-8

jwt:
  secret: ${JWT_SECRET}