server:
  port: ${PORT:8080}

spring:
  security:
    user:
      name: ${SWAGGER_USER}
      password: ${SWAGGER_PASS}
      roles: ${SWAGGER_ROLE}
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  massages:
    basename: massages
    encoding: UTF-8
  mail:
    host: smtp.yandex.ru
    port: 465
    username: ${EMAIL_USER}
    password: ${EMAIL_PASS}
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true

jwt:
  secret: ${JWT_SECRET}